type Product {
    id: ID
    name: String!,
    description: String
}

type Order {
    id: ID,
    products: [Product]!
    buyer: Customer!
}

type Customer {
    firstName: String!
    lastName: String!
    title: String
}

type Query {
    orders: [Order]
    products: [Product]
    customers: [Customer]
    order(id: ID) : Order
}